CXX = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -Wpedantic -g

uninitialized_value: uninitialized_value.cpp
	$(CXX) $(CXXFLAGS) uninitialized_value.cpp -o uninitialized_value

clean:
	rm -f uninitialized_value